// 'use client'
// "use client"
import { Geist, Geist_Mono, Bricolage_Grotesque, Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "./OverLay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const bricolage_Grotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// export const SidebarProvider = ({ children }) => {
//   const [isSidebarOpen, setIsSidebarOpen] = useState(false);

//   const toggleSidebar = () => {
//     setIsSidebarOpen(prev => !prev);
//   };
// }

// export const useSidebar = () => {
//   return useContext(SidebarContext);
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${bricolage_Grotesque.variable} antialiased`}
      >
        <Providers> 
        {children}
        </Providers>
      </body>
    </html>
  );
}
